# Generated by Django 4.2.13 on 2024-07-11 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='no_picture.jpg', max_length=255, verbose_name='image'),
        ),
    ]
